### PR TITLE
Corrected wunderfixer use of restx.AmbientThread class

### PR DESCRIPTION
**Pull request by UberEclectic**
Corrected problem with wunderfixer use of restx.AmbientThread class being out of sync with actual restx.AmbientThread parameter requirements.

1.4.1 05/14/2019
Made WunderStation class consistent with restx.AmbientThread parameters

### CODE REVIEW

**Comment by UberEclectic** [comment]
This same pull request now has the wmr300.py fixes re: the addition of .encode('utf-8') in wmr300.py for each call to to_sorted_string().  This was to fix backwards compatibility with Python2 for the development/4.0 branch.  Fix confirmed on Python3 first then on Python2.  All set.

**Comment by UberEclectic** [comment]
For posterity, if I am understanding correctly, this is the change from "queue" to "q" that led to wunderfixer also needing such a change:

https://github.com/weewx/weewx/commit/f1003407dcbdffc0b7416f7c709f9c510c0054fc#diff-3543cd71b0a5b03d640fdd68611c5e68

**Comment by tkeffer** [comment]
Leon,

This is a useful commit, but could you refactor it so it solves just the problem, without using 4 unrelated commits to do it? The clutter makes it very hard to debug later.

**Comment by UberEclectic** [comment]
Tom,
My Git skills are lacking.
I don't know how to delete changes, I only know how to revert them.  Happy to learn, but I haven't been able to figure it out on my own.  A previous time I tried deleting my branch and recreating it and that didn't really help.

Anyway, if you check the files and diffs you'll see it's only the relevant changes.

I can try submitting another pull request to see if it looks cleaner now that this one is closed.

**Comment by UberEclectic** [comment]
Started a new pull request. Didn't submit, because looks the same with same net effect but extra changes that were reverted.
So delete the branch on my end and copy back just the two files?  Is there an easier way?

**Comment by UberEclectic** [comment]
Reading now...

http://web.archive.org/web/20100213104931/http://blog.madism.org/index.php/2007/09/09/138-git-awsome-ness-git-rebase-interactive

**Comment by UberEclectic** [comment]
Rebase was a mess.
This was what worked:

https://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream

**Pull request closed without merging**
