### PR TITLE
Improved spurious rain detection and allow different rain counter size.

### PR DESCRIPTION
**Pull request by edi-x**
The spurious rain detection caused a wrong rain value in the immediately
following loop iteration. This has been fixed by ignoring spurious rain
counter values for the last_rain value.
My hardware does not use the asserted counter size of 0x1000. It wraps
around after 0xdc. Therefore it's now possible to use different
rain counter sizes in settings.

I have used the driver for several weeks and one wrap around occurred in this time. Everything worked as it should. However I had no spurious rain values while this period. So I have not tested all possible situations in that part of the implementation yet.

### CODE REVIEW

**Comment by edi-x** [comment]
@matthewwall , if you are doing the review it would be great if you could take special care of line 693:
`if last_rain - packet['rain'] < (rain_counter_size - 1) * rain_per_bucket_tip * 0.5`

I kept this mechanism nearly untouched. However I have seen some occurrences of not correct readings where this rule would not work correctly. Here are some examples:
```
Apr 24 02:37:01 server weewx[627]: fousb: ignoring spurious rain counter decrement (0x7190): new: 2.55 old: 6.51
Apr 26 17:37:01 server weewx[12787]: fousb: ignoring spurious rain counter decrement (0x7970): new: 2.55 old: 6.51
```
Please remember that my counter wraps around after 6.54 cm of rain. Perhaps you have an idea how wrong readings could be detected in a more precise way.

**Comment by edi-x** [comment]
This new solution has detected a wrong reading for my station in the meanwhile and unfortunately the code did not work as intended. It went in a loop after the detection. The plan was to break out of the loop after a second reading with the same value but something went wrong here.

Additionally the wrong reading itself was taken as real reading and the correct readings afterwards where detected as the spurious readings. This is due to the rules how spurious readings are detected. I will think about the situation once again. Perhaps I will find a better approach for the whole thing. At least I'm going to fix this bug.

Here are my logs:

```
Jul 17 18:29:45 server weewx[31357] DEBUG weewx.drivers.fousb: rainTotal 0.6000000000000001
Jul 17 18:30:33 server weewx[31357] DEBUG weewx.drivers.fousb: rainTotal 2.4000000000000004
Jul 17 18:30:33 server weewx[31357] DEBUG weewx.drivers.fousb: got rainfall of 1.80 cm (new: 2.40 old: 0.60)
Jul 17 18:30:33 server weewx[31357] INFO weewx.manager: Added record 2020-07-17 18:30:00 CEST (1595003400) to database 'weewx.sdb'
Jul 17 18:30:34 server weewx[31357] INFO weewx.manager: Added record 2020-07-17 18:30:00 CEST (1595003400) to daily summary in 'weewx.sdb'
Jul 17 18:30:39 server weewx[31357] DEBUG weewx.drivers.fousb: rainTotal 2.4000000000000004
Jul 17 18:31:27 server weewx[31357] DEBUG weewx.drivers.fousb: rainTotal 0.6000000000000001
Jul 17 18:31:27 server weewx[31357] INFO weewx.drivers.fousb: ignoring spurious rain counter decrement (0x4f80): new: 0.6000000000000001 old: 2.4000000000000004
Jul 17 18:32:15 server weewx[31357] DEBUG weewx.drivers.fousb: rainTotal 0.6000000000000001
Jul 17 18:32:15 server weewx[31357] INFO weewx.drivers.fousb: ignoring spurious rain counter decrement (0x4f90): new: 0.6000000000000001 old: 2.4000000000000004
Jul 17 18:33:04 server weewx[31357] DEBUG weewx.drivers.fousb: rainTotal 0.6000000000000001
Jul 17 18:33:04 server weewx[31357] INFO weewx.drivers.fousb: ignoring spurious rain counter decrement (0x4f90): new: 0.6000000000000001 old: 2.4000000000000004
Jul 17 18:33:52 server weewx[31357] DEBUG weewx.drivers.fousb: rainTotal 0.6000000000000001
Jul 17 18:33:52 server weewx[31357] INFO weewx.drivers.fousb: ignoring spurious rain counter decrement (0x4f90): new: 0.6000000000000001 old: 2.4000000000000004
Jul 17 18:34:40 server weewx[31357] DEBUG weewx.drivers.fousb: rainTotal 0.6000000000000001
Jul 17 18:34:40 server weewx[31357] INFO weewx.drivers.fousb: ignoring spurious rain counter decrement (0x4f90): new: 0.6000000000000001 old: 2.4000000000000004
Jul 17 18:35:28 server weewx[31357] DEBUG weewx.drivers.fousb: rainTotal 0.6000000000000001
Jul 17 18:35:28 server weewx[31357] INFO weewx.drivers.fousb: ignoring spurious rain counter decrement (0x4f90): new: 0.6000000000000001 old: 2.4000000000000004
```

**Comment by tkeffer** [comment]
Anything new on this?

**Comment by edi-x** [comment]
I would like to have an automatic test for the driver. I tried some different approaches to get one without a satisfying success. It will take more time than expected.

**Comment by edi-x** [comment]
I have made some bugfixes. Will send a new pull request.

**Pull request closed without merging**
