### PR TITLE
added 3 variablel for skin.conf: x_interval, x_label_spacing, y_label_spacing

### PR DESCRIPTION
**Pull request by paolobenve**
with x_interval the user can decide which time interval he/she wants to use in a given plot

### CODE REVIEW

**Comment by paolobenve** [comment]
added two more variables:
- x_label_spacing: specifies how many labels should be printed along the x-axis: 3 means a label every 3 vertical grid lines
- y_label_spacing: specifies how many labels should be printed along the y-axis: 3 means a label every 3 horizontal grid lines

**Comment by tkeffer** [comment]
This looks good. However, we will need documentation. Just a short description in the `[ImageGenerator]` section in the Customizing Guide will do.

This is too late for V3.7.0 (which should appear this weekend), but will appear in V3.8.

**Comment by paolobenve** [comment]
added reference in customizing guide

**Comment by paolobenve** [comment]
http://weewx.qumran2.net/ see what you can get

**Comment by tkeffer** [comment]
Merged into `development` branch with commit https://github.com/weewx/weewx/commit/f6940e93507a426b17a74e00033e2edb60e06f9c

**Comment by tkeffer** [comment]
One other comment: your PR did not work as committed. The variable `drawlabel` was referenced before assignment. Fixed in commit https://github.com/weewx/weewx/commit/2bbe581f0883675a08aaa1ce3cf0fc2d77ffa74a

**Pull request closed without merging**
