### PR TITLE
WM300 merges based on Matt's recent changes plus CameronD's history reset fixes.

### PR DESCRIPTION
**Pull request by UberEclectic**
Hoping this helps to get Cameron's fixes integrated, because it's working great and WMR300 users really would benefit from those changes.

Also, added my weewx_watchdog script as an example.

### CODE REVIEW

**Comment by tkeffer** [comment]
Thanks for your submission!

A few questions / comments:
1. I assume this has been tested for a while? 
2. Can you include comments on how to use these new options, at least in the comment section?
3. The watchdog script is too specific to the WMR300 to be included in the `examples` section. Besides, I'm not fond of these kinds of scripts, preferring to engineer a solution so the problems don't happen in the first place.

Thanks again.

**Comment by UberEclectic** [comment]
Hey,  Tom,

1. I've been running this "merged" wmr300.py with no issues for over a week, but Cameron has been running with his history clearing code for much longer than that.

2. There "new options" are really just defaults.  AFAICT, history clearing was always intended to be on/working, but wasn't.  And the rain counter warning percent should be fine at the default of 90% for any/all.   The code seems pretty well documented on those:

    # threshold at which the history will be cleared, specified as an integer
    # between 5 and 95, inclusive.
    DEFAULT_HIST_LIMIT = 20

    # threshold at which warning will be emitted.  if the rain counter exceeds
    # this percentage, then a warning will be emitted to remind user to reset
    # the rain counter.
    DEFAULT_RAIN_WARNING = 90

3. W.r.t. the weewx_watchdog, I agree proper fixes would be preferred, but bugs persist and as such the script is very handy.  The only thing WMR300 specific w.r.t. the notification for rain counter warning.  There have been numerous accounts on the alias where WeeWX is failing to report due to interceptor issues, exceptions due to strings when int/float was expected, etc.  Even without the "shutdown -r now" the watchdog script would be useful to notify people when WeeWX isn't reporting for ANY reason.   I do have an update to the script, however, plus a corresponding logrotate example, so never mind for now.  =D

**Comment by tkeffer** [comment]
Committed to branch `master` https://github.com/weewx/weewx/commit/73eff8757b2a78437dffaa6295d0c81df6ab4532

**Comment by tkeffer** [comment]
Would you mine taking a look at the copy of `wmr300.py` in the `development` branch? 

The `development` branch is a Python 3 port of weewx. As such, it can occasionally diverge quite a bit from the `master` branch. So, when I did a "catch up" merge of `master` into `development` I had to pick through all your changes. Hopefully, I got them right.

The only difference between the two versions of `wmr300.py` should be changes necessary to get it to run on Python 3 (as well as Python 2), so you can just drop replace it into your WeeWX V3.x sources.

**Comment by UberEclectic** [comment]
Hey, Tom, good to know.  I'll have a look today.
My system runs python2 by default, so I'm a little disadvantaged w.r.t. actually testing the development branch, but I'll mull over how I can better contribute in that respect.
Look for an update from me later today.

**Comment by UberEclectic** [comment]
Tom, one thing.  I don't know the background on this one. I inherited that 52 (instead of 42) from Cameron D, which I took as golden (argument from authority? HA! 😆):

@@ -114,7 +114,7 @@
	---- cameron's extra notes:
	
	Station will free-run transmitting data for about 100s without seeing an ACK.
	a6 will always be followed by 91 ca 45 42 but final byte may be 0, 20, 32, 67,
	a6 will always be followed by 91 ca 45 52 but final byte may be 0, 20, 32, 67,

**Comment by UberEclectic** [comment]
Based on this diff, wmr300.py changes are almost entirely cosmetic and good to go from what I can SEE.

https://github.com/weewx/weewx/compare/master...development?expand=1#diff-454ff26071c84941f52fd6a2744d00e0

**Comment by UberEclectic** [comment]
Tom, testing backward compatibility with python2 has failed.
I'll see if I can figure out a workaround, but please don't merge just yet:

May  9 10:27:30 nixie weewx[1562]: engine: Loading station type WMR300 (weewx.drivers.wmr300)
May  9 10:27:30 nixie weewx[1562]: engine: Caught unrecoverable exception in engine:
May  9 10:27:30 nixie weewx[1562]:     ****  No module named log
May  9 10:27:30 nixie weewx[1562]:     ****  Traceback (most recent call last):
May  9 10:27:30 nixie weewx[1562]:     ****    File "/usr/share/weewx/weewx/engine.py", line 884, in main
May  9 10:27:30 nixie weewx[1562]:     ****      engine = engine_class(config_dict)
May  9 10:27:30 nixie weewx[1562]:     ****    File "/usr/share/weewx/weewx/engine.py", line 72, in __init__
May  9 10:27:30 nixie weewx[1562]:     ****      self.setupStation(config_dict)
May  9 10:27:30 nixie weewx[1562]:     ****    File "/usr/share/weewx/weewx/engine.py", line 96, in setupStation
May  9 10:27:30 nixie weewx[1562]:     ****      __import__(driver)
May  9 10:27:30 nixie weewx[1562]:     ****    File "/usr/share/weewx/weewx/drivers/wmr300.py", line 788, in <module>
May  9 10:27:30 nixie weewx[1562]:     ****      from weeutil.log import logdbg, loginf, logerr, logcrt
May  9 10:27:30 nixie weewx[1562]:     ****  ImportError: No module named log
May  9 10:27:30 nixie weewx[1562]:     ****  Exiting.

**Comment by UberEclectic** [comment]
Tom, I'm on the fence about how to approach the logging issue.

I think a simple conditional around the handling of the log functions would do the trick, but on what condition?

Python version?

WeeWX version (e.g. version >= 4, then use the new weeutil.log functions, otherwise the local default)?

I see the other drivers are all in the same boat.  Happy to code a w/o into the wmr300.py, but want to do it in a way that you can endorse.

> import syslog
788d786
< from weeutil.log import logdbg, loginf, logerr, logcrt
791c789
< DRIVER_VERSION = '0.20'
---
> DRIVER_VERSION = '0.19rc6+f3+l2'
808a807,821
> def logmsg(level, msg):
>     syslog.syslog(level, 'wmr300: %s' % msg)
>
> def logdbg(msg):
>     logmsg(syslog.LOG_DEBUG, msg)
>
> def loginf(msg):
>     logmsg(syslog.LOG_INFO, msg)
>
> def logerr(msg):
>     logmsg(syslog.LOG_ERR, msg)
>
> def logcrt(msg):
>     logmsg(syslog.LOG_CRIT, msg)
>

**Comment by UberEclectic** [comment]
Submitted a separate pull, #406 for the logging issue.
I went with the python version checking, because it was way less code than checking the WeeWx version, so early in the driver.  Didn't want to be exposed to inability to log messages by doing the check for WeeWX version further down.

**Comment by UberEclectic** [comment]
BTW, development wmr300.py driver has been working fine on WeeWX 3.9.1 on Python 2.7.13 (with the logging changes that I mentioned on #406).
So at least it validates that your updates didn't break the driver on Python 2.
Sorry, I'm not currently equipped to test if those changes are also good for Python 3 and the full WeeWx v4.

**Comment by UberEclectic** [comment]
Tom, I am currently running from the Debian **release** packages on RPI.
I'll back up my DB and .conf and customized drivers and see about de-installing the packages and moving to the development version.
Then I can test the wmr300.py changes properly.
Aiming to have that done today.

**Comment by UberEclectic** [comment]
Tom, development branch of wmr300.py is working fine under python3.
Actually it was working fine under python2, as well, at least for history clearing and the ingest of the very first data record.  But then engine.py caught the exception from weeutil.py as noted in issue #408, before any further records could be ingested.

I had to switch to python3 in weewxd to work around that issue.

I did not change any other "#!/usr/bin/env python" or "#!/usr/bin/python" references (and there are a lot of them that essentially default to python2 on my system and likely will for quite some time to come.

**Pull request closed without merging**
