### PR TITLE
Extend imagegenerator.py to output graphs for last calendar year

### PR DESCRIPTION
**Pull request by evilbunny2008**
It'd be nice if this or something like it would be included in weeWX.

### CODE REVIEW

**Comment by tkeffer** [comment]
Thanks for your PR!

Something like this seems reasonable, but is there any way to generalize it? I can see requests for, "But I want last month," or, "What about 2 years ago?"

**Comment by evilbunny2008** [comment]
So, something like year=-1 for last year? Same with month=-1?

I've only ever known one calendar so this may be misleading to some.

**Comment by evilbunny2008** [comment]
Updated to use previous_month and previous_year

**Comment by tkeffer** [comment]
That's one way of doing it.

Another would be to adopt the cheetahgenerator model: allow images to be generated "By Day," "By Month," and "By Year."

**Comment by evilbunny2008** [comment]
Wouldn't that add a lot of complexity if all they want is last month/year?

**Comment by evilbunny2008** [comment]
How else can I get last calendar month/year images functionality without a feature like this?

**Comment by evilbunny2008** [comment]
I should have been clearer in my last post, I was hoping for something like SLE type functionality that can work with exacting periods in graphs, because I think it's the wrong thing to do to have last year/month/week/day generated and stored for every time period, but running graphs covering 2 or 3 times the period isn't the best visually either.

**Pull request closed without merging**
