### PR TITLE
Added APRS/CWOP packet DEBUG logging

### PR DESCRIPTION
**Pull request by W0CHP**
Had some CWOP/APRS posting issues...patched restx.py to log raw APRS/CWOP tnc_packets to DEBUG log facility.

### CODE REVIEW

**Comment by tkeffer** [comment]
Chip,

How about putting in a test for `debug=2` for your extra, extra logging. It would look something like:

```python
    if weewx.debug >= 2:
        syslog.syslog(syslog.LOG_DEBUG, "restx: %s: APRS Packet: %s" %
                                  (self.protocol_name, tnc_packet))
```

Similar additions could be made for the other upload protocols.

-tk

**Comment by W0CHP** [comment]
Adding that `if` statement to restx.py and changing my weeex.conf to `debug = 2` worked fine.

Good idea Tom!

**Comment by tkeffer** [comment]
Want to update the pull request?

-tk

**Comment by W0CHP** [comment]
All set! Commit hash cdfe171.

- Chip

**Pull request merged**
