### PR TITLE
Log user and groups (PR for issue #933)

### PR DESCRIPTION
**Pull request by vinceskahan**
Here's the PR for https://github.com/weewx/weewx/issues/933

This tests ok on mac and pi and vagrant vm.  Typical output for pi looks like the following.  Added the three lines under Debug to the output on system startup.

````
Feb 15 19:57:09 pi4 weewxd-ecowitt[688]: INFO __main__: Terminating weewx version 5.0.0
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: Initializing weewxd version 5.0.0
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: Command line: /home/pi/weewx-venv/lib/python3.9/site-packages/weewxd.py --log-label weewxd-ecowitt /home/pi/weewx-data/ecowitt.conf
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: Using Python 3.9.2 (default, Mar 12 2021, 04:06:34) #012[GCC 10.2.1 20210110]
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: Located at /home/pi/weewx-venv/bin/python3
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: Platform Linux-6.1.21-v8+-aarch64-with-glibc2.31
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: Locale: 'en_US.UTF-8'
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: Entry path: /home/pi/weewx-venv/lib/python3.9/site-packages/weewxd.py
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: WEEWX_ROOT: /home/pi/weewx-data
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: Configuration file: /home/pi/weewx-data/ecowitt.conf
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: User module: /home/pi/weewx-data/bin/user
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: Debug: 1
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: User:   pi
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: Group:  pi
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO __main__: Groups: adm dialout cdrom sudo audio video plugdev games users input render netdev gpio i2c spi pi
Feb 15 20:00:01 pi4 weewxd-ecowitt[2872]: INFO weewx.engine: Loading station type GW1000 (user.gw1000)
````

### CODE REVIEW

**Comment by tkeffer** [comment]
Opinion: are users likely to have privacy concerns if they start posting logs with all the groups their user belongs to?

What do we lose by just logging the effective group id?

**Comment by vinceskahan** [comment]
Matthew specifically asked me to add the group membership to (I'm guessing) aid in working the many user support issues we see re: access to attached peripherals.   I suppose you could add something to 'weectl debug' to make it more discretionary if you wanted to approach it that way perhaps.  Whatever you guys want is ok with me...

**Comment by tkeffer** [comment]
Thanks, Vince!

I included your additions in the `weectl` log as well.

**Comment by vinceskahan** [comment]
Thanks. Gary suggested maybe adding loop_on_init too for possibly a
different addition someday.

-----  ***@***.*** ----

**Comment by gjr80** [comment]
> Thanks. Gary suggested maybe adding loop_on_init too for possibly a
> different addition someday.
> 

Just to clarify, my suggestion to include logging of `loop_on_init` in a separate email to Vince was for a local patch to `weewxd.py` to help understand how `loop_on_init` was being processed (as something was clearly amiss). I've since found the bug in `weewxd.py` the fix of which is covered at #935. I don't see any great need to permanently log the state of `loop_on_init`.

**Pull request merged**
