### PR TITLE
Produce JSON output from the default skin

### PR DESCRIPTION
**Pull request by teeks99**
This is mostly the same data that is available in the rss.xml file that is already in the default skin. Adding a JSON file, that is a bit more machine-parseable, will allow others to consume it a bit more easily.

Example of what the rendered output looks like is:

```json
{
    "station":
    {
        "location": "University City, MO",
        "latitude": 38.68006,
        "longitude": -90.32814,
        "altitude (meters)": 137.0,
        "link": "https://w.teeks99.com"
    },
    "generation":
    {
        "time": "Thu, 01 Oct 2020 13:32:00 CDT",
        "generator": "weewx 4.1.1"
    },
    "current":
    {
        "temperature": {"value": 67.3, "units": "°F"},
        "dewpoint": {"value": 41.4872761332, "units": "°F"},
        "humidity": {"value": 39.0, "units": "%"},
        "heat index": {"value": 67.3, "units": "°F"},
        "barometer": {"value": 30.0472696314, "units": "inHg"},
        "wind speed": {"value": 2.67886214224, "units": "mph"},
        "wind gust": {"value": 3.70760684504, "units": "mph"},
        "wind direction": {"value": 47.2275066352, "units": "°"},
        "wind chill": {"value": 67.3, "units": "°F"},
        "rain rate": {"value": 0.0, "units": "in/h"},
        "inside temperature": {"value": 75.65, "units": "°F"},
        "void_end": null
    },
    "day":
    {
        "max temperature": {"value": 70.0, "units": "°F", "at": "11:48:53 AM"},
        "min temperature": {"value": 44.4, "units": "°F", "at": "07:00:31 AM"},
        "max dewpoint": {"value": 47.1915360245, "units": "°F", "at": "11:36:00 AM"},
        "min dewpoint": {"value": 39.4505036571, "units": "°F", "at": "06:56:11 AM"},
        "max humidity": {"value": 85.0, "units": "%", "at": "07:07:46 AM"},
        "min humidity": {"value": 38.0, "units": "%", "at": "01:15:08 PM"},
        "max barometer": {"value": 30.0551866819, "units": "inHg", "at": "12:50:00 PM"},
        "min barometer": {"value": 29.9546320012, "units": "inHg", "at": "12:37:02 AM"},
        "max wind speed": {"value": 4.56489409737, "units": "mph", "at": "10:56:00 AM"},
        "max wind gust": {"value": 7.82258565623, "units": "mph", "at": "11:54:00 AM"},
        "max rain rate": {"value": 0.0, "units": "in/h", "at": "12:00:02 AM"},
        "rain total": {"value": 0.0, "units": "in"},
        "max inside temperature": {"value": 76.73, "units": "°F", "at": "12:11:45 AM"},
        "min inside temperature": {"value": 74.21, "units": "°F", "at": "07:02:38 AM"},
        "void_end": null
    },
    "week":
    {
        "max temperature": {"value": 85.5, "units": "°F", "at": "02:55:25 PM (Sunday)"},
        "min temperature": {"value": 44.4, "units": "°F", "at": "07:00:31 AM (Thursday)"},
        "max dewpoint": {"value": 70.4834812317, "units": "°F", "at": "02:55:25 PM (Sunday)"},
        "min dewpoint": {"value": 39.4505036571, "units": "°F", "at": "06:56:11 AM (Thursday)"},
        "max humidity": {"value": 96.0, "units": "%", "at": "05:35:39 AM (Sunday)"},
        "min humidity": {"value": 30.0, "units": "%", "at": "04:48:02 PM (Wednesday)"},
        "max barometer": {"value": 30.0551866819, "units": "inHg", "at": "12:50:00 PM (Thursday)"},
        "min barometer": {"value": 29.6442646743, "units": "inHg", "at": "05:50:00 PM (Sunday)"},
        "max wind speed": {"value": 6.4509260525, "units": "mph", "at": "11:03:00 AM (Wednesday)"},
        "max wind gust": {"value": 9.88007506183, "units": "mph", "at": "02:36:00 PM (Wednesday)"},
        "max rain rate": {"value": 0.36, "units": "in/h", "at": "12:18:44 AM (Monday)"},
        "rain total": {"value": 0.76, "units": "in"},
        "max inside temperature": {"value": 82.49, "units": "°F", "at": "05:36:13 PM (Monday)"},
        "min inside temperature": {"value": 73.49, "units": "°F", "at": "06:56:25 AM (Sunday)"},
        "void_end": null
    },
    "month":
    {
        "max temperature": {"value": 70.0, "units": "°F", "at": "10/01/2020 11:48:53 AM"},
        "min temperature": {"value": 44.4, "units": "°F", "at": "10/01/2020 07:00:31 AM"},
        "max dewpoint": {"value": 47.1915360245, "units": "°F", "at": "10/01/2020 11:36:00 AM"},
        "min dewpoint": {"value": 39.4505036571, "units": "°F", "at": "10/01/2020 06:56:11 AM"},
        "max humidity": {"value": 85.0, "units": "%", "at": "10/01/2020 07:07:46 AM"},
        "min humidity": {"value": 38.0, "units": "%", "at": "10/01/2020 01:15:08 PM"},
        "max barometer": {"value": 30.0551866819, "units": "inHg", "at": "10/01/2020 12:50:00 PM"},
        "min barometer": {"value": 29.9546320012, "units": "inHg", "at": "10/01/2020 12:37:02 AM"},
        "max wind speed": {"value": 4.56489409737, "units": "mph", "at": "10/01/2020 10:56:00 AM"},
        "max wind gust": {"value": 7.82258565623, "units": "mph", "at": "10/01/2020 11:54:00 AM"},
        "max rain rate": {"value": 0.0, "units": "in/h", "at": "10/01/2020 12:00:02 AM"},
        "rain total": {"value": 0.0, "units": "in"},
        "max inside temperature": {"value": 76.73, "units": "°F", "at": "10/01/2020 12:11:45 AM"},
        "min inside temperature": {"value": 74.21, "units": "°F", "at": "10/01/2020 07:02:38 AM"},
        "void_end": null
    },
    "year":
    {
        "max temperature": {"value": 99.5, "units": "°F", "at": "06/06/2020 03:54:25 PM"},
        "min temperature": {"value": 4.3, "units": "°F", "at": "02/14/2020 06:43:22 AM"},
        "max dewpoint": {"value": 81.7890466069, "units": "°F", "at": "08/10/2020 01:13:20 PM"},
        "min dewpoint": {"value": -5.35709286239, "units": "°F", "at": "02/14/2020 08:45:00 AM"},
        "max humidity": {"value": 99.0, "units": "%", "at": "01/03/2020 03:08:05 AM"},
        "min humidity": {"value": 15.0, "units": "%", "at": "03/08/2020 01:41:07 PM"},
        "max barometer": {"value": 30.707351283, "units": "inHg", "at": "01/16/2020 10:45:00 AM"},
        "min barometer": {"value": 29.3065920153, "units": "inHg", "at": "06/09/2020 10:30:28 AM"},
        "max wind speed": {"value": 8.76055876761, "units": "mph", "at": "04/08/2020 07:45:00 PM"},
        "max wind gust": {"value": 17.5956603328, "units": "mph", "at": "03/29/2020 02:20:00 PM"},
        "max rain rate": {"value": 3.88, "units": "in/h", "at": "06/22/2020 08:14:28 PM"},
        "rain total": {"value": 36.88, "units": "in"},
        "max inside temperature": {"value": 89.78, "units": "°F", "at": "07/28/2020 04:37:05 PM"},
        "min inside temperature": {"value": 59.72, "units": "°F", "at": "02/21/2020 05:36:55 PM"},
        "void_end": null
    }
}
```

### CODE REVIEW

**Comment by tkeffer** [comment]
Hello, Thomas.

Thanks for putting the time into this. 

Do you have a use case for this? RSS is a very machine readable format in XML, which targets RSS readers. 

Is there some consumer that you are trying to target that requires JSON?

**Comment by teeks99** [comment]
I wanted to make an Android app that could consume this. I realize that I *could* parse the RSS, as it is a very clean format, however JSON is easier to deal with. Just separating the units out makes everything a lot easier on the client side, if conversions are desired there.

**Comment by tkeffer** [comment]
That sounds like a specialized application. I'm reluctant to include it in the core part of WeeWX without some specific reason, other than it is in JSON. Why not just make this into a simple extension?

**Comment by teeks99** [comment]
My hope was that this piece in here wouldn't be a "specialized application", but because JSON is so common for consuming data from across the web that anyone could utilize it. I could see people making interactive javascript pages that can compare data from multiple weather stations...with no server-side processing needed.

I was aware that this would be pretty easy to add to an extension, but I think there is a big benefit to having it in the default. Then this data source will be present with zero barrier to entry. Extensions are pretty easy to install, but I think it is still a high bar for some people. 

My personal story illustrates this. I installed weewx with very minor config when I got my first weather station about 9mo ago. For several months, I was content to just brows to the web app on my phone when I wanted to check the temp outside. However, one day I thought...hmm, maybe there's an Android app for this, that can give me status/notifications. Going to the google play store I found that there [was one](https://github.com/evilbunny2008/weeWXWeatherApp), but it required an extension to be installed on the server side....not the normal expected pre-reqs for getting an app from the android store....so I gave up on that and stuck with the webpage. 

Now that I got a bit of free time, I decided to see if there was a better experience. I started by installing some better skins, and it turned out to be very easy. If there is a good way to convince all new users (who may already be a bit overwhelmed by the current setup/config process) to just try extensions, that would be great, but not sure how to go about that. Instead, I'm hoping to make an app that will work for other people that don't have any extensions. I could make it work with the existing rss.xml file, but having the JSON there would be a lot better.

**Comment by tkeffer** [comment]
I think you're making my point. Your app doesn't exist yet, and, even when it does, this JSON format would target only it. You would still have the problem of how to upload the data to the app. 

What I do think would be useful is a standard real-time feed for LOOP and archive data, probably built on MQTT. The user would turn it on in `weewx.conf`, making the data available for any interested client. There are extensions that already do this, but I can see the utility in having one "standard" way, which all clients can depend on existing.

Matthew Wall's [MQTT extension](https://github.com/weewx/weewx/wiki/mqtt) is the closest we have to this. Why not have your app consume data from it? 

If installation is a barrier for users, I am open to including it as part of the standard distribution of WeeWX.

**Comment by teeks99** [comment]
Looking a bit a MQTT it looks like it needs a "broker" server in the middle to manage the topics coming from the sensor. There are definitely pros to this architecture,  but one negative is the need for a smart server.  One of the beauties of weewx is that there is just a bunch of static files that get served from a directory. 

Currently there are two (classes of) clients that can view that can consume the data coming out of these static files: web browsers and rss readers. The goal of this pull request is to provide an avenue for more classes of client: phone/desktop apps, dynamic Javascript web apps, bots that collect data. Clearly none of these exist yet, my hope is that adding this interface can lower the barrier to them existing. With this PR in place anything that can do a simple web query and parse JSON could become a client. 

That said, I do understand if you are hesitant to merge something that doesn't have any users yet. I can go and work this into an extension and start from that direction.

**Comment by teeks99** [comment]
In case anyone stumbles upon this thread, the skin I promised is available in the [weewx-json](https://github.com/teeks99/weewx-json) project. The wiki has been updated to include it.

**Pull request closed without merging**
