### PR TITLE
wee_database now only accepts 1 'verb' at a time

### PR DESCRIPTION
**Pull request by gjr80**
Refer #64. Not as clean as I would like due to optparse limitations but
seems to do the job.

### CODE REVIEW

**Comment by tkeffer** [comment]
Ooooh, that's some mighty fancy Python-foo!

**Comment by gjr80** [comment]
I'll tell that to the folks at Stackoverflow :)

**Comment by gjr80** [comment]
Was always told the job's not over till the paperwork is done so I guess I had best update the two wiki entries. Do I need to be given permission to edit the wiki or is having a GitHub account sufficient?

**Comment by tkeffer** [comment]
No permission necessary. Just edit away.

-tk

**Pull request merged**
