### PR TITLE
Correct nsteps

### PR DESCRIPTION
**Pull request by paolobenve**
This patch solves the problem discussed in https://groups.google.com/forum/#!topic/weewx-user/6gevHcrAoDk : a value of y min interval in yscale causes the yscale to have unwanted max values: the code used a value of 10 for nsteps, while here nsteps takes into account the y interval specified in yscale tuple, till a maximum value of 20 for the new nsteps

### CODE REVIEW

**Comment by tkeffer** [comment]
There are better ways to do this. See commit https://github.com/weewx/weewx/commit/e59d57ec1b9db74725068ab9d54196ea7ff2cf92.

To get what you want, set option `y_nticks=4`

**Comment by paolobenve** [comment]
I can't find y_nticks option in http://www.weewx.com/docs/customizing.htm ...

**Comment by tkeffer** [comment]
That's because the change has not been published yet. It will appear in v3.8.0.

If you want it now, checkout the `development` branch.

**Comment by paolobenve** [comment]
ok

However, in general, in order to propose some simple pull request, should I
start from master or development brach?


don Paolo Benvenuto

2017-04-27 15:06 GMT+02:00 Tom Keffer <notifications@github.com>:

**Comment by tkeffer** [comment]
Use `master` if it's a simple bug fix.

Use `development` if it's a new feature. This is a new feature.

**Pull request closed without merging**
