### PR TITLE
Add a layer of abstraction to StdQC

### PR DESCRIPTION
**Pull request by gjr80**
Taking a leaf out of the 'Ask for forgiveness, rather than permission' mantra...

Following on from @matthewwall #148 comments of 9 Sep, this PR adds a layer of abstraction to the `StdQC` service to allow other apps to hook into the underlying weewx QC system.

### CODE REVIEW

**Comment by tkeffer** [comment]
Can we move class `QC` into its own file so other things that want to use it don't have to import `engine.py`?

**Comment by gjr80** [comment]
Did mention that in my #148 comment but somehow missed that in this PR. You know my naming choices are poor, I don't see any other obvious candidates files/directories. I might need some direction here.

**Comment by tkeffer** [comment]
Ummm, ... `qc.py`? In the `bin/weewx` directory.

**Comment by gjr80** [comment]
Hmm, that was simple. I'll fix it now.

**Comment by tkeffer** [comment]
Thanks, Gary!

**Pull request merged**
