### PR TITLE
Added rsync patch from Kenneth Baker

### PR DESCRIPTION
**Pull request by W0CHP**
- Option to specify SSH key to use for rsync
    - Option to enable ssh/rsync compression
    - Example weewx.conf [[RSYNC]] skin/stanza config options:
        compress = True
        ssh_options = -i /home/weewx/weewx-id_dsa

### CODE REVIEW

**Comment by tkeffer** [comment]
The test will only work if the configuration file has `ssh_options` defined

**Comment by tkeffer** [comment]
Can you fix the problem with `ssh_options`?

**Comment by W0CHP** [comment]
Yep - I'll work on that! My family just moved, and we're getting everything settled over here ;-)

**Comment by tkeffer** [comment]
Any progress?

**Comment by W0CHP** [comment]
Sorry for the delay Tom.

OK - so what would you like the desired behavior to be, if the `sshd_options` are not defined? Bail and print an error, or continue as always without the options defined, where the `sshd_options` are simply appended to the  `cmd = ['rsync']` only if defined?

**Comment by tkeffer** [comment]
Sorry, I wasn't very clear with my comment. 

My concern is the test program at the end of the file. The lines

    rsync_upload = RsyncUpload(
                           rsync_dir,
                           config_dict['StdReport']['RSYNC']['path'],
                           config_dict['StdReport']['RSYNC']['server'],
                           config_dict['StdReport']['RSYNC']['user'],
                           config_dict['StdReport']['RSYNC']['port'],
                           config_dict['StdReport']['RSYNC']['ssh_options'],
                           config_dict['StdReport']['RSYNC'].as_bool('compress'))
    rsync_upload.run()

will raise an exception unless all options are defined in `weewx.conf`. One way I've dealt with this elsewhere is to use:

    rsync_upload = RsyncUpload(
                           rsync_dir,
                           **config_dict['StdReport']['RSYNC'])
    rsync_upload.run()

**Comment by W0CHP** [comment]
Ahhhh so the `**kwargs` idiom is alright with you, rather than hard-defining possible config dictionary items?

**Comment by W0CHP** [comment]
Tom, see commit fad4956 on this pull request. :-)

**Comment by tkeffer** [comment]
The unpacked dictionary idiom is used throughout weewx. It allows a user to pass arguments weewx is not aware of to underlying libraries.

Thanks for adding SSH support to this, Ken!

**Pull request merged**
