### PR TITLE
parameterize the statistics page

### PR DESCRIPTION
**Pull request by matthewwall**
parameterize the observations in statistics.inc

this results in:

 * less copy/paste of html and cheetah code
 * automatic display of observations so users do not have to modify the skin for 'extended' sensors

### CODE REVIEW

**Comment by tkeffer** [comment]
Two comments.

1. In at least two places, you should be able to replace 

    ```
    #set $units = '' if not $hasattr($unit.label, $x) else $getattr($unit.label, $x)
    ```
    with:

    ```
    #set $units = $getattr($unit.label, $x, '')
    ```
2. I'm still getting "Rain" in a "Totals" section, as well as the "Statistics" section:
    image

**Comment by matthewwall** [comment]
>     1. In at least two places, you should be able to replace

resolved in both places that pattern occurred

>     2. I'm still getting "Rain" in a "Totals" section, as well as the "Statistics" section:

the 'totals' module has been removed

**Comment by matthewwall** [comment]
a couple of things i noticed:

1) there is still a little duplication of data.  the 'current conditions' tracks day rainfall, as does the 'day' column of the summary statistics.  probably not a big deal.

2) the list of observations in the 'current conditions' module is not exactly the same as the list for summary statistics or full statistics.  i think this is ok, since the context matters.  i would like to prune the list in 'current conditions' even more, but there is no telling what is relevant or not for each user.  so i'm ok leaving it as it is.

**Comment by tkeffer** [comment]
Missing lots of translations! By my count:

```
Language cz
Section ['Labels']['Generic']
Missing in cz.conf: extraTemp4
Missing in cz.conf: extraTemp5
Missing in cz.conf: extraTemp6
Missing in cz.conf: extraTemp7
Missing in cz.conf: extraTemp8
Missing in cz.conf: extraHumid1
Missing in cz.conf: extraHumid2
Missing in cz.conf: extraHumid3
Missing in cz.conf: extraHumid4
Missing in cz.conf: extraHumid5
Missing in cz.conf: extraHumid6
Missing in cz.conf: extraHumid7
Missing in cz.conf: extraHumid8
Missing in cz.conf: leafTemp1
Missing in cz.conf: leafTemp2
Missing in cz.conf: leafWet1
Missing in cz.conf: leafWet2
Missing in cz.conf: luminosity
Missing in cz.conf: soilMoist1
Missing in cz.conf: soilMoist2
Missing in cz.conf: soilMoist3
Missing in cz.conf: soilMoist4
Missing in cz.conf: soilTemp1
Missing in cz.conf: soilTemp2
Missing in cz.conf: soilTemp3
Missing in cz.conf: soilTemp4
Section ['Texts']

-------------------

Language de
Section ['Labels']['Generic']
Missing in de.conf: extraTemp4
Missing in de.conf: extraTemp5
Missing in de.conf: extraTemp6
Missing in de.conf: extraTemp7
Missing in de.conf: extraTemp8
Missing in de.conf: extraHumid1
Missing in de.conf: extraHumid2
Missing in de.conf: extraHumid3
Missing in de.conf: extraHumid4
Missing in de.conf: extraHumid5
Missing in de.conf: extraHumid6
Missing in de.conf: extraHumid7
Missing in de.conf: extraHumid8
Missing in de.conf: leafTemp1
Missing in de.conf: leafTemp2
Missing in de.conf: leafWet1
Missing in de.conf: leafWet2
Missing in de.conf: luminosity
Missing in de.conf: soilMoist1
Missing in de.conf: soilMoist2
Missing in de.conf: soilMoist3
Missing in de.conf: soilMoist4
Missing in de.conf: soilTemp1
Missing in de.conf: soilTemp2
Missing in de.conf: soilTemp3
Missing in de.conf: soilTemp4
Section ['Texts']

-------------------

Language es
Section ['Labels']['Generic']
Missing in es.conf: extraTemp4
Missing in es.conf: extraTemp5
Missing in es.conf: extraTemp6
Missing in es.conf: extraTemp7
Missing in es.conf: extraTemp8
Missing in es.conf: extraHumid1
Missing in es.conf: extraHumid2
Missing in es.conf: extraHumid3
Missing in es.conf: extraHumid4
Missing in es.conf: extraHumid5
Missing in es.conf: extraHumid6
Missing in es.conf: extraHumid7
Missing in es.conf: extraHumid8
Missing in es.conf: leafTemp1
Missing in es.conf: leafTemp2
Missing in es.conf: leafWet1
Missing in es.conf: leafWet2
Missing in es.conf: luminosity
Missing in es.conf: soilMoist1
Missing in es.conf: soilMoist2
Missing in es.conf: soilMoist3
Missing in es.conf: soilMoist4
Missing in es.conf: soilTemp1
Missing in es.conf: soilTemp2
Missing in es.conf: soilTemp3
Missing in es.conf: soilTemp4
Section ['Texts']

-------------------

Language fr
Section ['Labels']['Generic']
Missing in fr.conf: extraTemp4
Missing in fr.conf: extraTemp5
Missing in fr.conf: extraTemp6
Missing in fr.conf: extraTemp7
Missing in fr.conf: extraTemp8
Missing in fr.conf: extraHumid1
Missing in fr.conf: extraHumid2
Missing in fr.conf: extraHumid3
Missing in fr.conf: extraHumid4
Missing in fr.conf: extraHumid5
Missing in fr.conf: extraHumid6
Missing in fr.conf: extraHumid7
Missing in fr.conf: extraHumid8
Missing in fr.conf: leafTemp1
Missing in fr.conf: leafTemp2
Missing in fr.conf: leafWet1
Missing in fr.conf: leafWet2
Missing in fr.conf: luminosity
Missing in fr.conf: soilMoist1
Missing in fr.conf: soilMoist2
Missing in fr.conf: soilMoist3
Missing in fr.conf: soilMoist4
Missing in fr.conf: soilTemp1
Missing in fr.conf: soilTemp2
Missing in fr.conf: soilTemp3
Missing in fr.conf: soilTemp4
Section ['Texts']

-------------------

Language gr
Section ['Labels']['Generic']
Missing in gr.conf: extraTemp4
Missing in gr.conf: extraTemp5
Missing in gr.conf: extraTemp6
Missing in gr.conf: extraTemp7
Missing in gr.conf: extraTemp8
Missing in gr.conf: extraHumid1
Missing in gr.conf: extraHumid2
Missing in gr.conf: extraHumid3
Missing in gr.conf: extraHumid4
Missing in gr.conf: extraHumid5
Missing in gr.conf: extraHumid6
Missing in gr.conf: extraHumid7
Missing in gr.conf: extraHumid8
Missing in gr.conf: leafTemp1
Missing in gr.conf: leafTemp2
Missing in gr.conf: leafWet1
Missing in gr.conf: leafWet2
Missing in gr.conf: luminosity
Missing in gr.conf: soilMoist1
Missing in gr.conf: soilMoist2
Missing in gr.conf: soilMoist3
Missing in gr.conf: soilMoist4
Missing in gr.conf: soilTemp1
Missing in gr.conf: soilTemp2
Missing in gr.conf: soilTemp3
Missing in gr.conf: soilTemp4
Section ['Texts']

-------------------

Language it
Section ['Labels']['Generic']
Missing in it.conf: extraTemp4
Missing in it.conf: extraTemp5
Missing in it.conf: extraTemp6
Missing in it.conf: extraTemp7
Missing in it.conf: extraTemp8
Missing in it.conf: extraHumid1
Missing in it.conf: extraHumid2
Missing in it.conf: extraHumid3
Missing in it.conf: extraHumid4
Missing in it.conf: extraHumid5
Missing in it.conf: extraHumid6
Missing in it.conf: extraHumid7
Missing in it.conf: extraHumid8
Missing in it.conf: leafTemp1
Missing in it.conf: leafTemp2
Missing in it.conf: leafWet1
Missing in it.conf: leafWet2
Missing in it.conf: luminosity
Missing in it.conf: soilMoist1
Missing in it.conf: soilMoist2
Missing in it.conf: soilMoist3
Missing in it.conf: soilMoist4
Missing in it.conf: soilTemp1
Missing in it.conf: soilTemp2
Missing in it.conf: soilTemp3
Missing in it.conf: soilTemp4
Section ['Texts']
Extra in it.conf: N/A

-------------------

Language nl
Section ['Labels']['Generic']
Missing in nl.conf: extraTemp4
Missing in nl.conf: extraTemp5
Missing in nl.conf: extraTemp6
Missing in nl.conf: extraTemp7
Missing in nl.conf: extraTemp8
Missing in nl.conf: extraHumid1
Missing in nl.conf: extraHumid2
Missing in nl.conf: extraHumid3
Missing in nl.conf: extraHumid4
Missing in nl.conf: extraHumid5
Missing in nl.conf: extraHumid6
Missing in nl.conf: extraHumid7
Missing in nl.conf: extraHumid8
Missing in nl.conf: leafTemp1
Missing in nl.conf: leafTemp2
Missing in nl.conf: leafWet1
Missing in nl.conf: leafWet2
Missing in nl.conf: luminosity
Missing in nl.conf: soilMoist1
Missing in nl.conf: soilMoist2
Missing in nl.conf: soilMoist3
Missing in nl.conf: soilMoist4
Missing in nl.conf: soilTemp1
Missing in nl.conf: soilTemp2
Missing in nl.conf: soilTemp3
Missing in nl.conf: soilTemp4
Section ['Texts']

-------------------

Language th
Section ['Labels']['Generic']
Missing in th.conf: extraTemp4
Missing in th.conf: extraTemp5
Missing in th.conf: extraTemp6
Missing in th.conf: extraTemp7
Missing in th.conf: extraTemp8
Missing in th.conf: extraHumid1
Missing in th.conf: extraHumid2
Missing in th.conf: extraHumid3
Missing in th.conf: extraHumid4
Missing in th.conf: extraHumid5
Missing in th.conf: extraHumid6
Missing in th.conf: extraHumid7
Missing in th.conf: extraHumid8
Missing in th.conf: leafTemp1
Missing in th.conf: leafTemp2
Missing in th.conf: leafWet1
Missing in th.conf: leafWet2
Missing in th.conf: luminosity
Missing in th.conf: soilMoist1
Missing in th.conf: soilMoist2
Missing in th.conf: soilMoist3
Missing in th.conf: soilMoist4
Missing in th.conf: soilTemp1
Missing in th.conf: soilTemp2
Missing in th.conf: soilTemp3
Missing in th.conf: soilTemp4
Section ['Texts']

```

**Comment by matthewwall** [comment]
translations added at commit f1d5f3bd

**Comment by matthewwall** [comment]
still trying to figure out a good way to conditionally generate plots.  basically need something like the `$year.OBSERVATION.has_data` conditional, so that the skin does not generate a zillion empty plots that will never be displayed.

**Comment by tkeffer** [comment]
> still trying to figure out a good way to conditionally generate plots. basically need something like the `$year.OBSERVATION.has_data` conditional, so that the skin does not generate a zillion empty plots that will never be displayed.

We could add an option to the `[ImageGenerator]` section in `skin.conf` that selects whether to generate the plot on the basis of whether there's any data in it. Something like

```ini
        [[[yearET]]]
            yscale = None, None, 0.02
            plot_type = bar
            conditional_generate=True
            [[[[ET]]]]
                aggregate_type = sum
                aggregate_interval = week
                label = Evapotranspiration (weekly total)

```

Actually, now that I think about it, the default for `conditional_generate` should be `True`.

**Comment by tkeffer** [comment]
Went with `skip_if_empty` instead. More self-explanatory. Default is `False`, so we don't break any old configurations. See commit https://github.com/weewx/weewx/commit/6408a33318b6d68760e7ec4c1002cf481a248fa8

Have at it!

**Comment by tkeffer** [comment]
Did `skip_if_empty` work for you? I haven't tested it very extensively.

If so, let's do the merge.

**Comment by tkeffer** [comment]
Gave it a try. I have an old-style "wview" schema, so it broke because a lot of the types are not included in it.

From the stack trace, it appears that it made it through the `CheetahGenerator`, but broke in the plot generation:

```
Sep 30 10:51:27 nuc wee_reports[78091] INFO weewx.cheetahgenerator: Generated 189 files for report I18NReport in 25.16 seconds
Sep 30 10:51:27 nuc wee_reports[78091] DEBUG weewx.manager: Daily summary version is 1.0
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.imagegenerator.ImageGenerator'
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****  extraHumid3
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****    File "/home/tkeffer/git/weewx/bin/weewx/reportengine.py", line 197, in run
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****      obj.start()
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****    File "/home/tkeffer/git/weewx/bin/weewx/reportengine.py", line 345, in start
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****      self.run()
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****    File "/home/tkeffer/git/weewx/bin/weewx/imagegenerator.py", line 42, in run
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****      self.genImages(self.gen_ts)
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****    File "/home/tkeffer/git/weewx/bin/weewx/imagegenerator.py", line 205, in genImages
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****      start_vec_t, stop_vec_t ,data_vec_t = weewx.xtypes.get_series(
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****    File "/home/tkeffer/git/weewx/bin/weewx/xtypes.py", line 112, in get_series
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****      raise weewx.UnknownType(obs_type)
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****  weewx.UnknownType: extraHumid3
Sep 30 10:51:28 nuc wee_reports[78091] ERROR weewx.reportengine:         ****  Generator terminated
```

So, I guess that `skip_if_empty` needs to be extended to include not only whether a type is non-null, but also whether it is included at all in the schema...

**Comment by tkeffer** [comment]
I modified the image generator so that if `skip_if_empty` is `True`, it will keep going if it encounters types that are not in the schema.  See branch https://github.com/weewx/weewx/tree/mwall_simplify_seasons.

It almost works now, but it's still referring to some plots in `index.html` that are not getting generated. Here's what it looks like (German locale): https://weewx.com/translations/de/

**Comment by tkeffer** [comment]
I've come to believe that the problem is peculiar to my database. I think everything is fine. 

I'll go ahead and merge this branch into `development`

**Pull request merged**
