### PR TITLE
Added section about WeeWX's BGR colour usage as no mention currently.

### PR DESCRIPTION
**Pull request by Zanderama**
Corrected a sentence which mentions 0x...... as RGB colour.

I may be interested in updating colours in config and documents to #RRGGBB if you want?  May remove some potential confusion vs 0xBBGGRR as a technicality? 

Cheers :)

### CODE REVIEW

**Comment by matthewwall** [comment]
> I may be interested in updating colours in config and documents to #RRGGBB if you want? May remove some potential confusion vs 0xBBGGRR as a technicality?

this one bit me too, a long, long time ago.

however, i do not think we should change the behavior from 0xBBGGRR to 0xRRGGBB.  better to just document it in both the skin.conf and docs.

**Comment by tkeffer** [comment]
Oh, and it's "color", not "colour". :-)

**Comment by Zanderama** [comment]
Hi, I'm not trying to make too big a deal of this, though at the moment the only mention of color in the HTML docs says 0xNNNNNN is RGB, so I wanted to clear that up.  That was confusing me for a while at least - hence my 'bug' report too.  Not many people may even have heard of BGR colors.

https://www.grammarly.com/blog/color-colour/  "The rest of the English-speaking world uses the longer form, colour" ... but I'll go with the flow :-D

Let me know if you want any help converting .conf colors etc to #RRGGBB etc

**Comment by Zanderama** [comment]
I'll have a go at a PR for changing .confs to #RRGGBB.

**Comment by Zanderama** [comment]
Hi,

I've created some one line scripts which change over the .htm and .conf files to #rrggbb.   Seem to work reliably.

Not sure how to push another change and PR before this one is accepted or rejected?

Cheers

**Pull request closed without merging**
