### PR TITLE
FineOffsetUSB Driver: Improved spurious rain detection and allow different rain counter size

### PR DESCRIPTION
**Pull request by edi-x**
The spurious rain detection caused a wrong rain value in the immediately
following loop iteration. This has been fixed by ignoring spurious rain
counter values for the last_rain value.
My hardware does not use the asserted counter size of 0x1000. It wraps
around after 0xdc. Therefore it's now possible to use different
rain counter sizes in settings.

### CODE REVIEW

**Comment by tkeffer** [comment]
@matthewwall is in charge of the fousb driver, so he will have to comment on the fix.

However, the test is not useful. You need to test the driver's code directly, not reproduce it in a test suite.

**Comment by edi-x** [comment]
The test was useful for me to get used to Python and the weewx environment. But sure you are right that this kind of test cannot be used in the future and does not test the fousb.py code itself. I took some time to get this clean. While doing so I added a detection for increased spurious values calculating the rain rate in the driver and setting a maximum rain rate of 50 cm/h (can be changed in the configuration). This can be very useful when stations work with loop data because spurious values usually result in a way too high rain rate in a 48 seconds period.

**Comment by tkeffer** [comment]
I'm sure it was useful to you, but it will not work as part of the test suite because, well, it doesn't anything.

Either change it so it does, or drop it from the PR.

**Comment by edi-x** [comment]
@tkeffer , I understood your first feedback for the original test version but I had already updated the test, see https://github.com/weewx/weewx/pull/612/commits/fa472605bbe2bdd0e03e3b8d61d8d3e802ed5563
In my opinion this version should be OK because now the test calls the relevant method directly from the fousb.py file. What are you still missing here?

**Comment by tkeffer** [comment]
@matthewwall is the one you have to please! He's in charge of the FO driver. I'm just making sure we end up with something that fits in the present test structure, and is maintainable.

1. Is it really necessary to include `testgen_fousb.conf` just to set two variables, one of which is ignored?

2. What is the function of the line
   ```python
           ts = ts
   ```

3. The test function should not print anything. I know there are exceptions to this, but generally test suites should be quiet unless there is something wrong.

**Comment by edi-x** [comment]
Done!

**Comment by tkeffer** [comment]
Good solution. Let's see what Matthew says.

**Comment by edi-x** [comment]
I took a look at my log files today to see how the changes perform. I didn't see any spurious readings, but I found two events with a too high rain rate.
```
Nov 16 09:37:51 server weewx[32445] DEBUG weewx.drivers.fousb: rainTotal 1.74
Nov 16 09:38:40 server weewx[32445] DEBUG weewx.drivers.fousb: rainTotal 1.74
Nov 16 09:39:28 server weewx[32445] DEBUG weewx.drivers.fousb: rainTotal 1.74
Nov 16 09:40:16 server weewx[32445] DEBUG weewx.drivers.fousb: rainTotal 1.74
Nov 16 09:40:16 server weewx[32445] INFO weewx.manager: Added record 2020-11-16 09:40:00 CET (1605516000) to database 'weewx.sdb'
Nov 16 09:40:16 server weewx[32445] INFO weewx.manager: Added record 2020-11-16 09:40:00 CET (1605516000) to daily summary in 'weewx.sdb'
Nov 16 09:40:17 server weewx[32445] DEBUG weewx.restx: StationRegistry: wait interval (110039 < 604800) has not passed for record 2020-11-16 09:40:00 CET (1605516000)
Nov 16 09:40:17 server weewx[32445] DEBUG weewx.reportengine: Running reports for latest time in the database.
Nov 16 09:40:17 server weewx[32445] DEBUG weewx.reportengine: Running report 'SmallImages'
Nov 16 09:40:17 server weewx[32445] DEBUG weewx.reportengine: Found configuration file /etc/weewx/skins/Images/skin.conf for report 'SmallImages'
Nov 16 09:40:17 server weewx[32445] DEBUG weewx.drivers.fousb: rainTotal 1.77
Nov 16 09:40:17 server weewx[32445] DEBUG weewx.drivers.fousb: ignoring current rainfall of 0.03 due to too high rain rate of 108.00
[...]
Nov 16 09:41:05 server weewx[32445] DEBUG weewx.drivers.fousb: rainTotal 1.77
Nov 16 09:41:05 server weewx[32445] DEBUG weewx.drivers.fousb: got rainfall of 0.03 cm (new: 1.77 old: 1.74)
```
I don't know how this can happen. The last loop (09:40:16) logged a value of 1.74 and one second later a new event is logged where the rain value has increased by 0.03. My first theory was that the new rain event has already been recognized by the station and it has been added to it's internal archive memory. Weewx reads the new value from there during the archiving procedure. However the driver distinguishes between the loop and the archive timestamps. So I don't understand right now why the rain rate is calculated for an increased value of 0.03 mm in one second (this would result in the logged rain rate of 108). Either the distinction between loop and archive timestamps is not correct or there is an additional loop call when the archive period has finished and archive values are calculated using the loop values!?

However, the next loop value with the value of 1.77 seems to arrive at 09:41:05 and is counted as a valid rain event. So In my case where the archived values should be calculated using the loop data the final result should be correct. If the values are taken from the stations memory I believe that the rain amount would also be calculated correct after the next archive period has completed.

One further point from the logs is that the wraparound seems to work correct:
```
Nov  3 20:13:18 server weewx[21209] DEBUG weewx.drivers.fousb: rainTotal 6.539999999999999
Nov  3 20:14:06 server weewx[21209] DEBUG weewx.drivers.fousb: rainTotal 0.0
Nov  3 20:14:06 server weewx[21209] INFO weewx.drivers.fousb: rain counter wraparound detected (0x8360): new: 0.0 old: 6.539999999999999 max: 6.54
Nov  3 20:14:06 server weewx[21209] DEBUG weewx.drivers.fousb: got rainfall of 0.03 cm (new: 0.00 old: 6.54)
Nov  3 20:14:55 server weewx[21209] DEBUG weewx.drivers.fousb: rainTotal 0.0
Nov  3 20:15:43 server weewx[21209] DEBUG weewx.drivers.fousb: rainTotal 0.0

[...]

Oct 16 08:47:09 server weewx[877] DEBUG weewx.drivers.fousb: rainTotal 6.539999999999999
Oct 16 08:47:57 server weewx[877] DEBUG weewx.drivers.fousb: rainTotal 0.0
Oct 16 08:47:57 server weewx[877] INFO weewx.drivers.fousb: rain counter wraparound detected (0xb2b0): new: 0.0 old: 6.539999999999999 max: 6.54
Oct 16 08:47:57 server weewx[877] DEBUG weewx.drivers.fousb: got rainfall of 0.03 cm (new: 0.00 old: 6.54)
Oct 16 08:48:45 server weewx[877] DEBUG weewx.drivers.fousb: rainTotal 0.0
```

**Comment by matthewwall** [comment]
edi-x, could you split this into two separate merge requests?  these would be the two merge requests:

1) add a configuration option to the fousb driver that sets the amount-of-rain-per-bucket-tip

2) implement a mechanism to deal with spurious rain values

the first one should be pretty easy.  the second one is not trivial.

**Comment by edi-x** [comment]
OK, I will prepare the two separate merge requests.

**Comment by edi-x** [comment]
I have created the pull request for the rain counter size part: https://github.com/weewx/weewx/pull/628

**Pull request closed without merging**
