### PR TITLE
add python shims for deprecated wee_commands for Issue #962

### PR DESCRIPTION
**Pull request by vinceskahan**
Here's a PR for starting to add those wee_xyz shims.

- I 'have' tested that poetry does the right thing and the shims seem to work ok for me (macos)
- I added edits to add them to the dpkg and rpm packages but have 'not' tested those additions

I didn't change any changelogs or software versions.  This PR is just the meat, so to speak.

Let me know if you want me to try to build/test the packages......

### CODE REVIEW

**Comment by tkeffer** [comment]
Unfortunately, this won't work for pip installs. For pip executables, you specify an entry point in the `pyproject.toml` file, then pip manufacturers a shim that calls an appropriate Python program. Both `weewxd` and `weectl` work this way. You can not just include an executable.

I don't see an easy way to make a single version that works for both the package installers and pip.

Frankly, I don't this added complexity is worth it, but maybe you can figure something simple out.

**Comment by vinceskahan** [comment]
Take another look at the diff. I added python scripts for each legacy
command, added them as entry points, and poetry did exactly what you said.
I also tested that the resulting shims worked.

-----  ***@***.*** ----

**Comment by tkeffer** [comment]
My apologies. I missed that completely. Moving too fast, too early in the morning!

**Comment by vinceskahan** [comment]
Minor additions to get the .deb package to generate the wrapped shims too.  Debian package looks ok for clean install.

**Comment by vinceskahan** [comment]
Tom at this point I *think* this one is good to go forward on.  Tests ok for pip, deb, rpm installations.   I did not test upgrades as I trust Matthew's upgrade wizardry logic.

If 5.next is imminent I'd suggest you slip this one in if possible.

**Comment by tkeffer** [comment]
This problem seems to have gone away as people have adapted to `weectl`.

**Pull request closed without merging**
