### PR TITLE
Address issue #346

### PR DESCRIPTION
**Pull request by gjr80**
Changes as per Matthew's email of 2 October. One change I found necessary though, `weecfg.prompt_for_driver_settings()` needs a `config_dict` to obtain the driver settings rather than `stn_info`.

Tested against a driver that does prompt for driver settings and one that does not. Both behaved as expected.

PS. Sorry about all the whitespace removal, but that must be a good thing musn't  it?

### CODE REVIEW

**Comment by tkeffer** [comment]
Looks good, except for one thing. There is also a call to `prompt_for_driver_settings()` in `setup.py`.

**Comment by gjr80** [comment]
Hmm, a flaw in my workflow. Working off a VM with an install from a branch does not give you a `setup.py`...

Fixed but have not tested this. I am not sure I see the need, but then again I am not well versed on `setup.py`

**Comment by tkeffer** [comment]
Looks good. What's with the dickin' around of the whitespace? Did some tool do that?

**Comment by gjr80** [comment]
My editor has a setting to automatically delete trailing whitespace on save. I turned it on after a few files a while ago had so much whitespace it bloated the file size.

**Comment by tkeffer** [comment]
What I (try to) do in that situation is do a commit with just the reformatting, then a commit with the recoding. That way, a reader doesn't have to wade through a bunch of non-relevant stuff to find the code changes.

**Comment by gjr80** [comment]
Ok, will make sure I do it properly next time.

**Comment by matthewwall** [comment]
i have seen this kind of whitespace thrashing before.  we are getting a lot of it in another project i'm working on where developers are using different versions of pycharm, or where they have their pycharm customized differently from everyone else.

some editors will automatically indent for you, but then they forget to remove the whitespace.  other editors (latest pycharm, i think) will flag that extraneous whitespace or just automatically remove it.

sometimes it is the indents, sometimes it is trailing whitespace (often leftover from removing a comment, or from copy-pasting from a shell or other environment into the editor - different editors handle copy-paste in different ways)

anyway, tom's suggestion about doing a single commit with formatting changes is a good one.  in practice, this means you should first open the file you intend to work on in your editor, run its 'lint' (or equivalent), save the file, then `git diff` to see if it tidied up anything.  if so, do the tidy-up commit.  then do your hacking.

**Comment by tkeffer** [comment]
These days, I'm using pycharm almost exclusively. It doesn't touch the whitespace unless you ask to reformat the file (`Ctrl-Alt-L`). 

If we all use the same formatting style, it should work well. Right now, mine is the default. Look in the top level project directory, file `.idea/codeStyles/codeStyleConfig.xml`. Mine reads

```xml
<component name="ProjectCodeStyleConfiguration">
  <state>
    <option name="PREFERRED_PROJECT_CODE_STYLE" value="Default" />
  </state>
</component>
```

it turn, the `Default` code style (look in `~/.PyCharm2018.2/config/codestyles/Default.xml`) is

```xml
<code_scheme name="Default" version="173">
  <Python>
    <option name="HANG_CLOSING_BRACKETS" value="true" />
  </Python>
  <codeStyleSettings language="Python">
    <option name="RIGHT_MARGIN" value="120" />
  </codeStyleSettings>
</code_scheme>
```

Matthew would probably prefer something smaller for `RIGHT_MARGIN`, but I figure what's the point of having a modern wide screen display if you can't use it!

**Pull request merged**
