### PR TITLE
added missing mentions of "min_ge"

### PR DESCRIPTION
**Pull request by clmcavaney**
I found that min_ge was missing from a few files.  These changes fix that.

### CODE REVIEW

**Comment by tkeffer** [comment]
Thanks. Don't know how that got missed.

Well, I do know: It seems to be missing from the test suites as well. If you've got the interest, perhaps you could add it? Just follow the pattern of one of its mates.

**Comment by clmcavaney** [comment]
Yep - will do.

**Comment by clmcavaney** [comment]
Done. Test file updated - not sure how to test the test files though.

**Comment by tkeffer** [comment]
Just type `make test` from the main weewx directory.

You'll have to supply the "correct" expected results as well.

**Comment by clmcavaney** [comment]
How do I modify the test values to ensure I get something other than a count of 0 for a month?
i.e. at least one minimum greater than 20 degrees C

**Comment by clmcavaney** [comment]
Righto - I think the tests are good and working.

**Comment by tkeffer** [comment]
Thanks, Chris! Nicely done.

I changed the "mild" condition from 65F to 59F, so that there would be some non-zero test values.

**Pull request merged**
