### PR TITLE
Do calculations in Cheetah templates using the #set directive

### PR DESCRIPTION
**Pull request by roe-dl**
I found it nowhere else explained and hope it is useful.

### CODE REVIEW

**Comment by vinceskahan** [comment]
http://cheetahtemplate.sourceforge.net/docs/users_guide_html/users_guide.html#SECTION000940000000000000000 explains it pretty well

**Comment by roe-dl** [comment]
But it does not explain the use of `weewx.units.ValueHelper` and `weewx.units.ValueTuple` in that circumstance. And if you do not use those classes the values are not formatted appropriately.

**Comment by roe-dl** [comment]
https://groups.google.com/g/weewx-user/c/_8Jix9BIuCA

**Comment by tkeffer** [comment]
I think a short section explaining how to manipulate values in the templates is a good idea, but I don't think this is the best example because there is already a tag for displaying the amount of daylight (`$almanac.sun.visible`).

**Comment by roe-dl** [comment]
Ok, I will think about a better example.

**Comment by roe-dl** [comment]
I thought about a better example for some time. There is already another example involving temperature, so I thought to stick to an example involving time. After all I the new example calculates the time between the beginning of civil twilight in the morning to the end of civil twilight in the evening, which is the time there is some light outside.

**Comment by tkeffer** [comment]
1. The code as written would not compile --- missing parenthesis.
2. HTML issues. A `<span>` block was closed with `</code>` instead of `</span>`.
3. Explaining the `.raw` suffix is not necessary because it is already defined elsewhere in the guide. Just provide a link.
4. Types `ValueHelper`, `ValueTuple`, and tag `$almanac` are all defined elsewhere but no links are provided.
5. The prose is choppy. For example, you warn how displaying units is "tricky", but never show what's special about your code to avoid those hazards.
6. The example of difference in Kelvin (vs Celsius) is, well, tricky, because your solution won't work if the user were to innocently try it with Fahrenheit:
    `C_to_F(20 - 10) ≠ C_to_F(20) - C_to_F(10)`

**Comment by roe-dl** [comment]
To item 6.: The values are converted to Celsius within the tags. So the difference is always in Celsius. And for the Celsius scale differences are marked "K" or "Kelvin" instead of "°C" by convention. But anyway, this is about how to make calculated values formattable, so unit issues can confuse there. I removed the unit and let it to WeeWX to include the appropriate unit.

To item 5: I changed the text a little bit and added some additional explanation. Is that what you looked for? Should I provide more details?

**Comment by tkeffer** [comment]
Still didn't compile. The format override also had errors. 

In general, it's always a good idea to check any example code so as to avoid confusing the reader.

I fixed those problems, plus tried to improve the readability. See if you like the results.

**Comment by tkeffer** [comment]
I mistakenly did that push from my own copy of the repository, instead of your fork, so it includes a few extra things. Hopefully, you'll get the idea.

**Comment by roe-dl** [comment]
Yes, I like it. Thank you.

**Pull request merged**
