### PR TITLE
Implement format_data() in RESTThread

### PR DESCRIPTION
**Pull request by dcapslock**
Implements format_data() in RESTThread to allow a subclass of RESTThread to use REST APIs which require posting of data while still using the rest of the base class functions.

### CODE REVIEW

**Comment by dcapslock** [comment]
While that works it means that they specialising class needs to unnecessarily deal with creating the request etc. Using the logic that default process_record can deal with get and post cases, without handling process_record in the specialising class makes it cleaner. Otherwise, why not do all this work in get_record?

**Comment by tkeffer** [comment]
That makes sense. Thank you!

**Comment by tkeffer** [comment]
Resurrecting this PR. 

Are you actually using this capability? The present implementation only allows urlencoded POSTs. I would like to extend it to allow JSON POSTs.

**Comment by dcapslock** [comment]
Yes. The OpsGenie extension is using this. I can update that as required.

________________________________

**Comment by tkeffer** [comment]
It would not be hard to provide backwards compatibility, but if you're the only one using it (true, as far as I can tell), I'd rather keep it simple.

**Comment by tkeffer** [comment]
So long as they have their own version of process_record, it should not be a problem.

**Comment by tkeffer** [comment]
OK, try this one on for size: https://github.com/weewx/weewx/compare/1f99010b2f493ba25fb9092aaf7510d0b7760f43...development

To provide a POST body, you override function `get_post_body()`. It should return a 2-way tuple (body, mime_type).

The default version calls `format_data()` and packages any result as a MIME-type of `application/x-www-form-urlencoded`, thus maintaining backwards compatibility

**Pull request merged**
