### PR TITLE
Add last_year and last_year_todate to xstats.py

### PR DESCRIPTION
**Pull request by evilbunny2008**
Add last_year and last_year_todate to xstats.py to do comparisons to of rainfall up to this time last year, and for generating statistics for the last calendar year

### CODE REVIEW

**Comment by evilbunny2008** [comment]
Ok, I updated the PR to include extra details in the readme.txt but it looks like there is other stale information in it as it only include details on how to install into /home/weewx

**Comment by tkeffer** [comment]
I'm sorry, but your PR has a syntax error (missing paren on line 98), which makes me wonder if it has been tested.

Please fix, then extend the file `index.html.tmpl` to include the new keywords, then test.

**Comment by evilbunny2008** [comment]
It looks like I made a c&p mistake when I edited the file on github, I currently use the code on my website. I'll email you the URL.

As for the changes to index.html.tmpl time has gotten away from me tonight, will do it in the morning.

**Comment by evilbunny2008** [comment]
I overwrote my local copy with the copy in github and the index template and both seem to work fine now.

**Comment by tkeffer** [comment]
As this has a "new feature," I merged this into the `development` branch. To appear in V3.9

**Pull request closed without merging**
