### PR TITLE
Auto reboot CC3000 if station stops sending observations.

### PR DESCRIPTION
**Pull request by chaunceygardiner**
[Tom, creating another branch was not helping with the list of commits — which were me pulling from upstream to stay in sync.  I have now reset hard from upstream and my fork is now showing as 1 commit ahead.  I hope this looks fine on your end.]

One of my two CC3000s stopped sending observation values today. I had to reset the device to return it to normal operation. This PR automatically reboots the device when this occurs.

This appears to be extremely rare, but must have been observed at least once before as existing code detected and logged it.

### CODE REVIEW

**Comment by chaunceygardiner** [comment]
I am at a loss as to how to stop this from showing 58 commits.

**Comment by gjr80** [comment]
I have this happen occasionally as well, I am attuned to it now so always keep an eye on what is in my commits and PRs. My solution has been to blow away my fork and create a new one, keeping a local copy of whatever code you have changed of course. I then push my local changes to my fork and create a PR from there. Maybe heavy handed/over the top but given my limited git knowledge it is the easiest and simplest way I have found so far.

**Comment by chaunceygardiner** [comment]
Hey, I got it down to 1 commit!

**Comment by tkeffer** [comment]
Yippee!

You tested this under Python 2 and 3?

**Comment by tkeffer** [comment]
John, maybe you can tell us how you got it down to one commit?

**Comment by chaunceygardiner** [comment]
HI Tom,

Thank you for taking my change.  It was tested with Python 2 and 3.

As it turns out, I had not pushed the change yet after resetting to head.  So, the hard reset to upstream worked, I just need to actually finish doing it.

The steps are:
git remote add upstream git@github.com:weewx/weewx.git
git fetch upstream
git checkout master
git reset --hard upstream/master  
git push origin master --force
copy back your saved work (possibly a stash, but I just copied my one file elsewhere).
Then the normal git commit and push to my fork and create the PR.

Gary, thanks for your help.  Having said that, I’m glad I didn’t have to delete the fork.

**Comment by chaunceygardiner** [comment]
BTW, all my friends tell me that I should have been able to squash the commits with a:
git rebase -I HEAD~58. (changing all but the first pick to a squash)
git push -force

But I couldn’t get it to work.  And they will all tell you I was doing something wrong.

**Comment by tkeffer** [comment]
They say that git is a dirt simple storage model with a complicated set of commands. I believe it.

**Pull request merged**
